<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Tyuiu_NurpeisovaAK.Sprint0.Task5.V0</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu,NurpeisovaAK.Sprint0.Task5.V0.Lib\Tyuiu.NurpeisovaAK.Sprint0.Task5.V0.Lib.csproj" />
  </ItemGroup>

</Project>
